### ISSUE TITLE
Initialize contract v2 environment and specs

### ISSUE THREAD

**Issue by lumtis** [zeta-chain/protocol-contracts#198]
This epic groups tasks toward the goal of:

- Having first usable implementation of v2 contracts
- Completing specs
- Having a usable environment to start experimenting applications
- Having CI initialize with Solidity dev best practices (Slither, Fuzzing, Coverage)

```[tasklist]
### Tasks
- [ ] https://github.com/zeta-chain/protocol-contracts/issues/165
- [ ] https://github.com/zeta-chain/protocol-contracts/issues/174
- [ ] https://github.com/zeta-chain/protocol-contracts/issues/180
- [ ] https://github.com/zeta-chain/protocol-contracts/issues/189
- [ ] https://github.com/zeta-chain/protocol-contracts/issues/192
- [ ] https://github.com/zeta-chain/protocol-contracts/issues/193
- [ ] https://github.com/zeta-chain/protocol-contracts/issues/194
- [ ] https://github.com/zeta-chain/protocol-contracts/issues/195
- [ ] https://github.com/zeta-chain/protocol-contracts/issues/196
- [ ] https://github.com/zeta-chain/protocol-contracts/issues/197
- [ ] https://github.com/zeta-chain/protocol-contracts/issues/255
```

**Comment by lumtis** [comment]
All issues completed
