### ISSUE TITLE
Enable full-environment for v2 contracts

### ISSUE THREAD

**Issue by lumtis** [zeta-chain/protocol-contracts#258]
Extend https://github.com/zeta-chain/protocol-contracts/issues/198 mostly focus on first implementation to track task we should complete to be production ready for v2 contracts.

- Make CI complete for all security processes
- Add all scripts for workflow (deploy, etc...)
- New changes based on protocol integration

```[tasklist]
### Tasks
- [ ] https://github.com/zeta-chain/protocol-contracts/issues/156
- [ ] https://github.com/zeta-chain/protocol-contracts/issues/158
- [ ] https://github.com/zeta-chain/protocol-contracts/issues/204
- [ ] https://github.com/zeta-chain/protocol-contracts/issues/229
- [ ] https://github.com/zeta-chain/protocol-contracts/issues/236
- [ ] https://github.com/zeta-chain/protocol-contracts/issues/250
- [ ] https://github.com/zeta-chain/protocol-contracts/issues/251
- [ ] https://github.com/zeta-chain/protocol-contracts/issues/253
- [ ] https://github.com/zeta-chain/protocol-contracts/issues/255
- [ ] https://github.com/zeta-chain/protocol-contracts/issues/279
- [ ] https://github.com/zeta-chain/protocol-contracts/issues/275
- [ ] https://github.com/zeta-chain/protocol-contracts/issues/274
- [ ] https://github.com/zeta-chain/protocol-contracts/issues/271
- [ ] https://github.com/zeta-chain/protocol-contracts/issues/299
- [ ] https://github.com/zeta-chain/protocol-contracts/issues/302
- [ ] https://github.com/zeta-chain/protocol-contracts/issues/306
- [ ] https://github.com/zeta-chain/protocol-contracts/issues/307
- [ ] https://github.com/zeta-chain/protocol-contracts/issues/308
- [ ] https://github.com/zeta-chain/protocol-contracts/issues/309
- [ ] https://github.com/zeta-chain/protocol-contracts/issues/310
```

**Comment by lumtis** [comment]
Closing now, added the revert support in localnet here: https://github.com/zeta-chain/node/issues/2745
