### ISSUE TITLE
Finalize `node/v20.0.2` branch

### ISSUE THREAD

**Issue by lumtis** [zeta-chain/protocol-contracts#387]
Remaining issue for the branch:

```[tasklist]
### Tasks
- [ ] Revert uint64 fix from https://github.com/zeta-chain/protocol-contracts/pull/378
- [ ] Disable ZETA functions
- [ ] Backport ERC20Custody upgradable
- [ ] Disallow `callOnRevert` option usage
```
